version: '3'

services:
  crunchy_bot:
    build: .
    container_name: crunchy_bot
    image: crunchy_bot
    restart: unless-stopped
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"